### ISSUE TITLE
Menu Window with all windows in application process

### ISSUE THREAD

**Issue by Loulou007** [vdelachaux/UI-with-Classes#3]
Hi @vdelachaux 

a really top framework to have "form class" !

I tried; and I have a problem with the Window menu item

I open all windows with 	
`DIALOG ( "myForm" ;  $data ;  *  ) `
in application process

My windows are displayed in the "Window" menu,.
Imagine, I open 3 times "Customers". I have 3 entries "Customers" in menu Window. OK.
If I bring a window to the front, the watermark is not updated.

It's possible to modify the name of entry in menu window? Or to avoid some windows in this menu?

BR

Louis

**Comment by vdelachaux** [comment]
Hi Louis
> It's possible to modify the name of entry in menu window? Or to avoid some windows in this menu?

I didn't plan to do this because I've never had to deal with that case (everyone has their own method...). 

But I think it would be possible to call the windows() function with a second object parameter that gives directives as you wish. Including, perhaps, a window callback formula that would give the name it wants displayed...

If you implement this, I'd be grateful if you'd submit a pull request so that everyone can benefit from it.

**Comment by Loulou007** [comment]
Hi Vincent,

I seen you answer a bit late ;) If I do it, I will submit it
